

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI3.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class alphasupermarketEntities : DbContext
{
    public alphasupermarketEntities()
        : base("name=alphasupermarketEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Endereco> Endereco { get; set; }

    public virtual DbSet<Estoque> Estoque { get; set; }

    public virtual DbSet<ItemPedido> ItemPedido { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Produto> Produto { get; set; }

    public virtual DbSet<StatusPedido> StatusPedido { get; set; }

    public virtual DbSet<TipoPagamento> TipoPagamento { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

}

}

