//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI3.Database
{
    using System;
    using System.Collections.Generic;
using System.Web.Mvc;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Endereco = new HashSet<Endereco>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int idCliente { get; set; }
        public string nomeCompletoCliente { get; set; }
		public string emailCliente { get; set; }
        public string senhaCliente { get; set; }
        public string CPFCliente { get; set; }
        public string celularCliente { get; set; }
        public string telComercialCliente { get; set; }
        public string telResidencialCliente { get; set; }
        public Nullable<System.DateTime> dtNascCliente { get; set; }
        public Nullable<bool> recebeNewsLetter { get; set; }
    
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
