//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI3.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int idEndereco { get; set; }
        public int idCliente { get; set; }
        public string nomeEndereco { get; set; }
        public string logradouroEndereco { get; set; }
        public string numeroEndereco { get; set; }
        public string CEPEndereco { get; set; }
        public string complementoEndereco { get; set; }
        public string cidadeEndereco { get; set; }
        public string paisEndereco { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
