
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI3.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Pedido
{

    public Pedido()
    {

        this.ItemPedido = new HashSet<ItemPedido>();

    }


    public int idPedido { get; set; }

    public int idCliente { get; set; }

    public byte idStatus { get; set; }

    public System.DateTime dataPedido { get; set; }

    public byte idTipoPagto { get; set; }

    public Nullable<int> idEndereco { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual Endereco Endereco { get; set; }

    public virtual ICollection<ItemPedido> ItemPedido { get; set; }

    public virtual StatusPedido StatusPedido { get; set; }

    public virtual TipoPagamento TipoPagamento { get; set; }

}

}
