
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI3.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Produto
{

    public Produto()
    {

        this.ItemPedido = new HashSet<ItemPedido>();

    }


    public int idProduto { get; set; }

    public string nomeProduto { get; set; }

    public string descProduto { get; set; }

    public decimal precProduto { get; set; }

    public Nullable<decimal> descontoPromocao { get; set; }

    public int idCategoria { get; set; }

    public string imagemProduto { get; set; }

    public string ativoProduto { get; set; }

    public Nullable<int> idUsuario { get; set; }

    public Nullable<int> qtdMinEstoque { get; set; }

    public byte[] imagem { get; set; }



    public virtual Categoria Categoria { get; set; }

    public virtual Estoque Estoque { get; set; }

    public virtual ICollection<ItemPedido> ItemPedido { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
