
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI3.Database
{

using System;
    using System.Collections.Generic;
    
public partial class TipoPagamento
{

    public TipoPagamento()
    {

        this.Pedido = new HashSet<Pedido>();

    }


    public byte idTipoPagto { get; set; }

    public string descTipoPagto { get; set; }



    public virtual ICollection<Pedido> Pedido { get; set; }

}

}
