
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI3.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public Usuario()
    {

        this.Produto = new HashSet<Produto>();

    }


    public int idUsuario { get; set; }

    public string loginUsuario { get; set; }

    public string senhaUsuario { get; set; }

    public string nomeUsuario { get; set; }

    public string tipoPerfil { get; set; }

    public Nullable<bool> usuarioAtivo { get; set; }



    public virtual ICollection<Produto> Produto { get; set; }

}

}
